- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: java setup
  ansible.builtin.import_role:
    name: common
    tasks_from: java-setup.yaml

- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml

- name: enable and start shipping
  ansible.builtin.service:
    name: shipping
    state: started
    enabled: yes 

- name: installing mysql client # we loop this at top in install maven task
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: install python dependencies
  ansible.builtin.pip: 
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - PyMySQL
  - cryptography 
    

- name: loading data or schema or import shipping data 
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: "{{ MYSQL_HOST }}"
    login_user: root
    login_password: RoboShop@1
    target: "{{ item }}"
  loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql

- name: restarting shipping
  ansible.builtin.service:
    name: shipping
    state: restarted
  