; [localhost]
; localhost

[mongodb]
mongodb-dev.tsmvr.fun

[catalogue]
catalogue-dev.tsmvr.fun

[redis]
redis-dev.tsmvr.fun


[user]
user-dev.tsmvr.fun 

[cart]
cart-dev.tsmvr.fun 

[mysql]
mysql-dev.tsmvr.fun 

[shipping]
shipping-dev.tsmvr.fun 

[rabbitmq]
rabbitmq-dev.tsmvr.fun 

[payment]
payment-dev.tsmvr.fun 

[frontend]
frontend-dev.tsmvr.fun 


