- name: enable nginx 1.24
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

    
- name: enable and start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes 


- name: removeing directory 
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: createing directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory


- name: downloading the frontend code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip
  

- name: unzip the code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html 
    remote_src: yes

- name: removeing default nginx conf
  ansible.builtin.file:
    state: absent
    path: /etc/nginx/nginx.conf
    

- name: copy the conf file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf



- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted


