- name: Create a system user 
  ansible.builtin.user:
      name: roboshop
      comment: "roboshop system user" 
      home: /app        
      shell: /sbin/nologin  
      system: yes           
      state: present

- name: delete app directory # deleting before creating bcz if developer change the code 
  ansible.builtin.file:
    path: /app
    state: absent    

- name: Create app directory 
  ansible.builtin.file:
    path: /app
    state: directory

- name: delete {{ component }} zip file   # delete before downloading again
  ansible.builtin.file:
    path: /tmp/{{ component }}.zip
    state: absent

- name: Download {{ component }} code 
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: /tmp/{{ component }}.zip

- name: unzip the code 
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
    remote_src: yes
